# DB Basis
FROM mariadb:latest

# Credentials im Image definieren (Aufgabenforderung)
ENV MARIADB_ROOT_PASSWORD=CHANGE_ME_ROOTPW

# Optional aber praktisch (falls db.php auf eine DB zeigt)
# ENV MARIADB_DATABASE=appdb

# Port-Doku
EXPOSE 3306