#cloud-config
# source: https://thenewstack.io/deploy-a-kubernetes-cluster-on-ubuntu-server-with-microk8s/
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin, microk8s
    home: /home/ubuntu
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCUBo+qnNu5xxM9vfz4C04M36FHxHNrEMdm5TkFj1/SfVtqunlUOeMpu7nFCZZKnX8HYwf/MkjcBiTYAgncxku8grwl6XuW/pcvmb6/ghSIaw4xtRRSzit7omqJ5d8kXB3+Nd1aaMHsjfly4nkaqswhySVXQqr8Hw6DbWVw8jLLVKEE+5NZHY33hJkhJwK4blCllsGpmQaKi1qxjsN0hZOWNK01iJAydwD8t2xJ0NOYbq8Qas5IyPnRN7SPxvEhIP6WLQ6Ym6Dmf8FwNW1cHLTKabgjzt5f/HKUkKS89dPd3fn4nnFli1BOMECGUIvVlOw2pQNri7+04OOfn2FGlqr5 teacher
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCv5Fb1iSks8agUcXwIpvcadlQ92ejppySxQeBM3hjgDL621q/i0uGiRYF4JxR19mX6zOC4Xze7xZ1wiEMF6lZIu9W7+DslfBN5sKZxLYeycrmmUN0zoSAEfB8kjYh2ZmoofzXzIyqdurBVfuHzJPjEQPgc41PEy6AXScoWJIDsvgKrxuDWijmX40fwkquiFrsPfW+XWJJnnLmsd9qsxBiy0nkE27WHFikJaOuKSqwBiWUjXcoyjGqpcJpwutFwaJNbJyIIkwDZlSZ9G/AjiZAdapNGkU+faH0HJH9Xqib3cQOg31qEt7JDnkV+UlS/RwsYD8EHdO6eu0pZ8ZLrgUeZQaLT5lgczt9SR/dRRBJ9Qub3iAoLlxpCg8J3MRJIom5PNSWYh9CM18ClPiDlAgkrMpEL6ePXsXTZoxSg9GE5tx0N87PX3t3SUCaoKmFAD15feg0ug4y270Nj4wqeVSHX4EjNX3+QP9mArbBnAMBBfIJ5riRt7wEpXcl0cTFdeLUWtO2Jv5beRK7wpA4PJpdBpTEmrFIh9O8ZuQ3jrAHyjccC7YcVg9nbJMYfH5E6tPlrtJcLmktWxzIJcZRNytOOyFTjCG0umym5MxqBtiryw++qofMO4LtekKGZb+dteq3VfSoDbPi+tXCpI+e33YJ+V752XXlskf1l14i7mhto0Q== mael.seewald@adnovum.ch

groups:
  - microk8s
system_info:
  default_user:
    groups: [microk8s]
ssh_pwauth: false
disable_root: false
package_update: true
package_upgrade: true
packages:
  - curl
runcmd:
  - sudo snap install microk8s --classic
  - mkdir /home/ubuntu/.kube
