services:
  web:
    container_name: m347-kn04b-web
    image: michaeleatontbz/kn02b-web:kn02b-web
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      kn04b-net:

  db:
    container_name: m347-kn04b-db
    image: michaeleatontbz/kn02b-db:kn02b-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: rootpwd
      MARIADB_DATABASE: kn04db
      MARIADB_USER: kn04user
      MARIADB_PASSWORD: kn04pass
    volumes:
      - db_data_b:/var/lib/mysql
    networks:
      kn04b-net:

networks:
  kn04b-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          ip_range: 172.31.10.0/24
          gateway: 172.31.10.254

volumes:
  db_data_b: